export const guideContent = {
  sections: [
    {
      heading: `Why most beginners lose the same way`,
      paragraphs: [
        `Beginners lose money in Aviator for remarkably predictable reasons. The game is simple, the rounds are fast, and the feedback loop is designed to pull you toward a handful of behaviours that feel right in the moment and cost you over time. The good news is that almost every common mistake is avoidable once you can name it.`,
        `What follows are the seven mistakes we see again and again from new players. None of them require special skill to fix. They require discipline, which is harder, but at least the fix is clear. If you can avoid these seven, you will already be playing better than the large majority of people who try the game.`,
      ],
    },
    {
      heading: `Mistake 1: Chasing losses`,
      paragraphs: [
        `Chasing losses is the single fastest way to go broke in a crash game. The pattern is universal: you lose a few rounds, you feel the pull to "win it back," so you increase your bet size or hold out for a higher multiplier to recover in one shot. The result is that your largest bets tend to happen at exactly the moments when you are most frustrated and least disciplined.`,
        `The problem is mathematical. Larger bets do not change your probability of winning; they only scale your losses when the round inevitably crashes. A player who doubles their bet after every loss will either win a small amount back or, far more often, hit a losing streak that wipes the entire bankroll in a few rounds. Crash games produce long losing streaks routinely, so this strategy fails with certainty given enough rounds.`,
        `The fix is to treat every round as independent and to predetermine your bet size before the session. If you lose, the answer is not a bigger bet. It is the same bet, or a smaller one, or walking away.`,
      ],
    },
    {
      heading: `Mistake 2: Not using auto-cashout`,
      paragraphs: [
        `Aviator lets you cash out manually by clicking the button, and it also lets you set an automatic cashout at a multiplier of your choosing. Far too many beginners rely on manual cashout alone, and it costs them. The reason is that crash games are engineered to make you hesitate. When the multiplier climbs past your intended target, the temptation to hold on for just a little more is enormous, and the round often crashes before you click.`,
        `Auto-cashout removes that hesitation. You decide your target in a calm moment before the round, set it, and the system executes it mechanically at the exact multiplier you chose. It turns a discipline problem into an automatic one.`,
        `The fix is to set an auto-cashout on every bet, even if you also plan to cash out manually. Decide your target based on your strategy and your bankroll, not on the adrenaline of a rising multiplier. The only person who benefits from your indecision is the house.`,
      ],
    },
    {
      heading: `Mistake 3: Betting too much per round`,
      paragraphs: [
        `Bet sizing is where casual play turns into rapid ruin. Because rounds last only seconds and you can bet on every one, a bet size that feels small can drain your bankroll in minutes. A player with 100 units who bets 20 units per round is risking a fifth of their bankroll on each of many rounds; a short losing streak ends the session immediately.`,
        `A sensible guideline is to never risk more than about 5% of your bankroll on a single round, and considerably less is safer. That keeps any one round, or any short streak, from being catastrophic, and it gives you the hundreds of rounds you need for variance to play out instead of ending your session on the first bad stretch.`,
        `The fix is to set your bet size as a fraction of your bankroll and to recalculate it as your balance changes. Small, consistent bets are the difference between a session that lasts an evening and one that lasts three rounds.`,
      ],
    },
    {
      heading: `Mistake 4: Trusting predictor apps and signals`,
      paragraphs: [
        `There is a thriving market of apps, Telegram channels, and Discord servers that claim to predict Aviator crashes or sell "signals" telling you when to cash out. None of them work. They cannot work, because each Aviator round is generated by a provably fair random system whose outcome is locked in before the round begins and is not knowable in advance.`,
        `Anyone selling crash predictions is selling the impossible. Some of these services show cherry-picked winning screenshots to build trust, then charge subscription fees or, worse, funnel players toward scam casinos through referral links. The "wins" they display are either fabricated or the statistical noise you would expect from random guessing.`,
        `The fix is to treat every predictor, bot, signal group, and hack as a scam by default. If a tool could actually predict rounds, selling it for a few dollars a month would make no sense; the seller would simply play and become wealthy. The fact that they sell signals instead of using them tells you everything.`,
      ],
    },
    {
      heading: `Mistake 5: Ignoring bankroll management`,
      paragraphs: [
        `Bankroll management is not glamorous, which is why beginners skip it. But it is the one skill that reliably determines how long you get to play and how often you walk away with something left. Players who treat their entire deposit as a single pool to bet from, with no plan and no limits, almost always lose it faster than they expected.`,
        `Good bankroll management means deciding in advance how much you are willing to lose in a session, how much you will bet per round, and at what point you will stop whether you are winning or losing. It means treating the money as an entertainment budget you have already decided to spend, not as an investment you expect to grow.`,
        `The fix is to set a session bankroll, a stop-loss, and a stop-win before you start playing, and to respect them even when you do not feel like it. We cover the exact system in our bankroll management guide.`,
      ],
    },
    {
      heading: `Mistake 6: Playing while tilted or emotional`,
      paragraphs: [
        `"Tilt" is the state of making decisions driven by emotion rather than logic, usually after a frustrating run of results. In Aviator, tilt shows up as bigger bets, higher cashout targets, and refusal to quit. The faster the rounds, the faster tilt compounds, because there is no natural pause to cool down between bets.`,
        `The danger of tilt is that it converts ordinary variance into catastrophic losses. A losing streak is statistically normal and survivable if you keep your bet sizes steady. The same streak becomes a disaster if, in frustration, you raise your bets and chase a recovery. The emotional response, not the streak itself, is what empties the bankroll.`,
        `The fix is to recognise the early signs, irritability, the urge to bet bigger, the feeling that you are "due" a win, and to treat them as a hard signal to stop. Walking away for even ten minutes breaks the loop. The rounds will still be there later.`,
      ],
    },
    {
      heading: `Mistake 7: Not understanding that rounds are independent`,
      paragraphs: [
        `This is the most common and the most stubborn misunderstanding in crash games. Players look at a string of low crashes and conclude that a high multiplier is "due," or they see a few big multipliers and assume the game is "hot." Both beliefs are false. Every Aviator round is an independent event. The crash point of the previous round has no influence whatsoever on the next one.`,
        `This is the gambler's fallacy, and it is built into how provably fair games work. Each round is generated from its own nonce against the committed seed, so the outcome is freshly random every time. A run of ten low crashes does not make the eleventh more likely to be high. The probability of reaching 2x is about 48.5% on every single round, regardless of what came before.`,
        `The fix is to never adjust your bets based on recent history. Past results are not a signal. The streak you are looking at is a story your brain is telling you about randomness, not a pattern that exists in the game. Bet your plan, not your interpretation of the last few rounds.`,
      ],
    },
  ],
  faqs: [
    {
      question: `Which beginner mistake loses money the fastest?`,
      answer: `Chasing losses by raising bet sizes after a losing streak empties a bankroll faster than anything else. Because crash games produce long streaks routinely, a doubling strategy fails with near-certainty. Keep bet sizes steady regardless of recent results.`,
    },
    {
      question: `Is manual cashout really worse than auto-cashout?`,
      answer: `For most players, yes. Manual cashout tempts you to hold on past your target for a little more, and the round usually crashes before you click. Auto-cashout executes your plan mechanically and removes the hesitation that costs beginners money.`,
    },
    {
      question: `Can looking at recent results help me pick a better cashout target?`,
      answer: `No. Each Aviator round is independent, so past crashes tell you nothing about the next round. Adjusting bets based on recent history is the gambler's fallacy. Your cashout target should come from your bankroll plan, not from the last few results.`,
    },
    {
      question: `If predictor apps do not work, why are there so many of them?`,
      answer: `Because they are profitable for the people selling them, not for the players buying them. They earn money from subscription fees and from referral commissions when they send players to certain casinos. The product does not need to work; it only needs to be sold.`,
    },
  ],
};
