export const guideContent = {
  sections: [
    {
      heading: `How to use this glossary`,
      paragraphs: [
        `Aviator and crash games come with their own vocabulary, and some of it overlaps with general casino terms in confusing ways. This glossary defines every term you will meet playing Aviator, in plain English. If a word in a guide or in the game left you unsure, it is almost certainly defined here.`,
        `We have kept the definitions short and honest. Where a term is widely misunderstood, like "provably fair" or "RTP," we say what it actually means rather than what the marketing implies. Use this as a reference; you do not need to read it end to end.`,
      ],
    },
    {
      heading: `A to C`,
      paragraphs: [
        `Auto-cashout: A feature that automatically cashes out your bet at a multiplier you choose in advance. It removes the need to click manually and prevents the hesitation that causes players to miss their target.`,
        `Bankroll: The total amount of money you have set aside for playing. A "session bankroll" is the portion allocated to a single session, separate from money you need for anything else.`,
        `Bet: The amount of money you place on a single round. In Aviator you can place up to two bets on the same round, each with its own cashout setting.`,
        `Cash Out: The action of collecting your winnings at the current multiplier before the round crashes. Your payout equals your bet multiplied by the multiplier at the moment you cash out.`,
        `Client seed: A random value contributed by the player and used, alongside the server seed and nonce, to generate a provably fair round. Because you control it, the operator cannot predict the outcome.`,
        `Crash: The moment a round ends and the multiplier stops climbing. If you have not cashed out before the crash, you lose your bet on that round.`,
      ],
    },
    {
      heading: `H to M`,
      paragraphs: [
        `House edge: The mathematical advantage the operator holds, expressed as a percentage. Aviator's house edge is 3%, meaning the game is structured to keep 3% of all wagered money over the long run.`,
        `Multiplier: The number your bet is multiplied by if you cash out in time. It starts at 1.00x and rises during the round; cashing out at 2.00x doubles your bet, at 10.00x it multiplies it by ten.`,
      ],
    },
    {
      heading: `N to P`,
      paragraphs: [
        `Nonce: Short for "number used once." A counter that increments by one each round, used with the server seed and client seed to generate a unique provably fair result for every round.`,
        `Provably fair: A cryptographic system that lets players verify each round was not tampered with, using a committed server seed, a player-controlled client seed, and a nonce. It proves fairness; it does not remove the house edge.`,
      ],
    },
    {
      heading: `R to S`,
      paragraphs: [
        `RTP (Return to Player): The percentage of all wagered money the game is designed to return to players over the long run. Aviator's RTP is 97%, so it returns 97 units per 100 wagered across a very large number of rounds.`,
        `Server seed: A secret random value generated by the operator and committed to in advance via its hash. It is revealed only when you rotate to a new seed, so you can verify past rounds without being able to predict future ones.`,
        `SHA-256: A widely used cryptographic hash function that produces a fixed fingerprint from any input. It is used to commit to the server seed before a round and to verify it afterwards. The same algorithm secures Bitcoin.`,
      ],
    },
    {
      heading: `V to W`,
      paragraphs: [
        `Volatility: Also called variance. A measure of how spread out a game's results are. In Aviator your cashout target controls the volatility: low multipliers mean frequent small wins, high multipliers mean rare large wins. The RTP stays the same either way.`,
        `Wagering requirement: A condition attached to casino bonuses that states how many times you must bet the bonus amount before you can withdraw it. A "30x" requirement on a bonus means you must wager thirty times the bonus value first.`,
        `Wagering contribution: The percentage of each bet that counts toward a wagering requirement. Different games contribute differently; for example, slots may count 100% while crash games or table games may count less or nothing at all, which materially affects how quickly you can clear a bonus.`,
      ],
    },
    {
      heading: `A few terms worth extra clarity`,
      paragraphs: [
        `A handful of these terms cause the most confusion, so they deserve a second, sharper look. RTP is not a promise about your session; it is a long-run average, and short sessions can vary wildly above or below it. Provably fair does not mean the game favours you; it means the round was generated honestly and can be checked. The house edge and RTP are two views of the same number, since house edge is simply 100 minus RTP.`,
        `Finally, do not confuse wagering requirements with the game itself. A casino bonus with a high wagering requirement and a low crash-game contribution can be effectively worthless, because clearing it requires wagering far more than the bonus is worth, all at the house's mathematical advantage. Always read both the requirement and the contribution before accepting any bonus.`,
      ],
    },
  ],
  faqs: [
    {
      question: `What is the difference between RTP and house edge?`,
      answer: `They are two views of the same number. RTP is the percentage returned to players; house edge is the percentage kept by the operator. Since Aviator's RTP is 97%, its house edge is 3%. Knowing either one tells you the other.`,
    },
    {
      question: `What does "provably fair" actually guarantee?`,
      answer: `It guarantees that each round was generated honestly from its seeds and was not altered after betting closed. It does not guarantee you will win or remove the 3% house edge; it only proves the round itself was not rigged.`,
    },
    {
      question: `What is a wagering requirement on a bonus?`,
      answer: `It is the amount you must bet before bonus winnings can be withdrawn, usually expressed as a multiple of the bonus. A 30x requirement means wagering thirty times the bonus value, and crash games may contribute only partially toward clearing it.`,
    },
    {
      question: `Should I use auto-cashout or cash out manually?`,
      answer: `Auto-cashout is almost always better for most players, because it executes your target mechanically and prevents the hesitation that causes you to miss a cashout before the crash. You can run auto-cashout on one bet and play manually with the other.`,
    },
  ],
};
