export const guideContent = {
  sections: [
    {
      heading: "What Is Aviator and How Does a Round Work?",
      paragraphs: [
        "Aviator is a crash game built by Spribe and licensed to hundreds of online casinos. The concept is deliberately simple: a small red airplane takes off and a multiplier starts climbing from 1.00x. The longer the plane stays in the air, the higher the multiplier goes. Your job is to cash out before the plane flies away, at which point the round crashes and anyone still in the round loses their bet. If you cash out at 2.00x on a 1 unit bet, you get 2 units back (1 unit of profit). If the round crashes at 1.87x before you cash out, you lose your stake.",
        "Every round is generated by a provably fair random number generator. This is the single most important fact about the game and the thing most new players misunderstand. The crash point for each round is decided before the round even starts, and it is locked in by a cryptographic hash that the casino publishes in advance. There is no dealer, no live person, and no decision being made in real time. The multiplier you see rising is just a visual representation of a number that was already chosen. Each round is completely independent of the round before it, which means there is no streak to read and no momentum to react to.",
        "A full round takes only a few seconds. There is a short betting window (usually around five seconds), then the plane takes off and the multiplier climbs, then the round ends either when the last player cashes out or when the predetermined crash point is hit. The next betting window opens immediately after. Because rounds are so short, it is easy to play a hundred of them in a single session, which is part of why bankroll discipline matters so much from your very first session.",
      ],
    },
    {
      heading: "Placing Bets and Understanding the Bet Panel",
      paragraphs: [
        "Before each round, you have a few seconds to place one or two bets. Aviator lets you run two independent bets at the same time, each with its own stake, its own auto-cashout target, and its own cash-out button. This dual-bet feature is the backbone of most real strategies, because it lets you hedge by taking a small, safe win on one bet while chasing a larger multiplier on the other.",
        "To place a bet, type your stake into the bet box (or use the plus and minus buttons to nudge it up or down), then click the large Bet button. Once the round starts, that same button turns into a Cash Out button showing your current live payout. If you set an auto-cashout target, the bet will cash out automatically the instant the multiplier reaches your target, with no click required. The minimum stake is usually around 0.10 in your account currency, and the maximum varies by casino but is typically a few hundred or a few thousand units.",
        "The numbers you set matter a lot more than the animation you watch. A common beginner mistake is to get so absorbed in the rising multiplier that they forget they have not set an auto-cashout, then scramble to click Cash Out in time. Setting your stake and auto-cashout during the betting window, before the round starts, removes that pressure entirely. Treat the betting window as your decision moment and the flight itself as just the result playing out.",
      ],
    },
    {
      heading: "Cashing Out: Manual vs Auto-Cashout",
      paragraphs: [
        "You have two ways to exit a round. Manual cash out means you click the Cash Out button whenever you decide the multiplier is high enough. Auto-cashout means you tell the game a target multiplier in advance (say, 2.00x) and the software cashes you out automatically the moment the multiplier reaches it. Both produce the exact same payout for the same multiplier, but they feel very different in practice.",
        "Manual cash out feels exciting because you are reacting in real time, but it is where most beginners lose money. Human reaction time is around 200 to 300 milliseconds, and the multiplier in Aviator climbs fast enough that you will frequently cash out lower than you intended, or miss the window entirely and lose the round. Worse, manual cash out tempts you into holding on for just a little more, which is how a winning position turns into a total loss. Auto-cashout removes both problems: it executes the instant your target is hit, and it forces you to commit to a plan before emotion gets involved.",
        "Our strong recommendation for new players is to use auto-cashout for every round and to pick a target before the round begins. You can always run a second bet manually if you want the thrill of timing a cash out, but your core strategy bet should be on autopilot. If you find yourself unable to resist holding for a higher multiplier, that is precisely the moment auto-cashout is saving you from yourself.",
      ],
    },
    {
      heading: "Reading the Live Stats Panel and Bet History",
      paragraphs: [
        "Above or beside the main game screen you will see a row of colored numbers showing the crash points of recent rounds, something like 1.34x, 4.82x, 1.05x, 2.17x, 1.52x. This is the round history, and below it the live panel shows every player currently in the round, their stake, their cashout multiplier if they cashed out, and their profit. It looks like useful information, and many players treat it as such, but you should understand exactly what it is and is not.",
        "The round history is real data, but it has no predictive value. Because each round is independent, the fact that the last five rounds all crashed under 2x tells you nothing about the next round. This is not a disclaimer or a hedge, it is the literal mathematical truth: the crash point of round six is decided by a fresh random number that has zero relationship to rounds one through five. Reading patterns into this row is the single most common way new players talk themselves into bad bets.",
        "What the live panel is genuinely useful for is sizing up the room. You can see how many players are betting, what stakes are common, and how aggressively the field is cashing out. Watching other players for a few minutes before you bet is a good way to get comfortable with the pace of the game. Just do not mistake any of it for a signal about what the next multiplier will be.",
      ],
    },
    {
      heading: "Putting It Together: Your First Session",
      paragraphs: [
        "For your first session, set a fixed budget you are fully prepared to lose, pick a single bet size of around 1 to 2 percent of that budget, and use auto-cashout at a modest target like 1.50x or 2.00x. Play one bet per round at first, even though the dual-bet feature is available, so you can focus on the mechanics rather than juggling two positions. Do this for 20 or 30 rounds and then stop, whether you are up or down.",
        "The goal of your first session is not to win money. It is to internalize the rhythm of the game, confirm that auto-cashout works the way you expect, and watch how often the multiplier reaches your target versus how often it crashes early. You will likely notice that crashes under 2x happen roughly half the time, which is exactly what the math predicts. Seeing that pattern in your own play is the foundation for every strategy guide on this site.",
        "After that first session, read our strategy and bankroll management guides before playing again. Aviator is a fast game with a built-in house edge, and the players who last are the ones who treat it as a controlled entertainment expense rather than a money-making opportunity. The mechanics are simple to learn in five minutes; the discipline takes longer, and it is worth more than any tip or trick you will ever read.",
      ],
    },
  ],
  faqs: [
    {
      question: "Is Aviator rigged or can the casino change the crash point mid-round?",
      answer:
        "No. Aviator uses a provably fair system where the crash point for each round is locked in by a cryptographic hash before the round starts, and the casino cannot change it. You can verify any round yourself using the published server seed, client seed, and nonce.",
    },
    {
      question: "What is the best auto-cashout multiplier for a beginner?",
      answer:
        "For your first sessions, a target between 1.50x and 2.00x is a reasonable starting point. It wins roughly half to two thirds of the time, which keeps the variance manageable while you learn the mechanics. You can adjust based on your own results and risk tolerance.",
    },
    {
      question: "Can I place two bets at the same time in Aviator?",
      answer:
        "Yes. Aviator supports two independent bets per round, each with its own stake and auto-cashout target. Many players use this to take a safe cashout on one bet while chasing a larger multiplier on the other.",
    },
    {
      question: "What happens if I do not cash out before the plane flies away?",
      answer:
        "You lose your entire stake for that bet. There is no partial payout and no second chance, which is exactly why setting an auto-cashout target in advance is safer than trying to time a manual cash out.",
    },
  ],
};
