import type { Metadata } from "next";
import Link from "next/link";
import {
  constructMetadata,
  faqSchema,
  breadcrumbSchema,
} from "@/lib/seo";

export const metadata: Metadata = constructMetadata({
  title: "Aviator Live: How Live Multipliers & Betting Work (2026)",
  description:
    "What 'Aviator live' really means: shared rounds, live chat, and the real-time betting panel. Why watching live rounds cannot help you predict the next crash, and how to practice for free.",
  path: "/aviator-live",
});

const liveFaqs = [
  {
    question: "Can I watch Aviator live?",
    answer:
      "Yes. When you open Aviator at a casino, you see each round happen live in real time. The plane takes off, the multiplier climbs, and it crashes at a point everyone watching sees at the same moment. You can also watch without betting, which is a good way to get comfortable with the pacing before you risk money.",
  },
  {
    question: "What is live Aviator?",
    answer:
      "Live Aviator refers to the multiplayer features built into the game: every player in a room sees the same round at the same time, there is a live chat window, and a panel shows other players' bets, cash out points, and winnings as they happen. It is the same provably fair game with a social layer on top.",
  },
  {
    question: "Can I see other players' bets?",
    answer:
      "Yes. Aviator shows a live betting panel listing who has placed a bet this round, their stake, and the multiplier at which they cashed out (or whether the round crashed before they cashed out). This is transparency, not a strategy tool, since what other players do has no effect on your round.",
  },
  {
    question: "Does watching live rounds help me win?",
    answer:
      "No. Each round is an independent event generated by a provably fair RNG, so the result of past rounds has zero influence on the next one. Watching a streak of high or low crashes and betting based on a 'pattern' is the gambler's fallacy. Live viewing helps you understand the pace and feel of the game, not predict outcomes.",
  },
];

export default function AviatorLivePage() {
  const breadcrumb = breadcrumbSchema([
    { name: "Home", url: "/" },
    { name: "Aviator Live", url: "/aviator-live" },
  ]);

  return (
    <>
      {/* Hero */}
      <section className="relative overflow-hidden border-b border-border">
        <div className="pointer-events-none absolute -right-40 -top-20 h-96 w-96 rounded-full bg-primary/10 blur-[120px]" />

        <div className="relative mx-auto max-w-4xl px-4 pb-16 pt-16 sm:px-6 lg:pb-20 lg:pt-20">
          {/* Breadcrumb */}
          <nav className="mb-8 flex items-center gap-2 text-sm text-muted-foreground">
            <Link href="/" className="transition-colors hover:text-foreground">
              Home
            </Link>
            <span aria-hidden>/</span>
            <span className="text-foreground">Aviator Live</span>
          </nav>

          <span className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-4 py-1.5 text-sm font-medium text-primary">
            Updated July 2026
          </span>

          <h1 className="mt-6 max-w-3xl text-4xl font-bold leading-[1.1] tracking-tight md:text-5xl">
            What does &quot;Aviator live&quot; actually mean?
          </h1>

          <p className="mt-5 max-w-2xl text-lg text-muted-foreground">
            Aviator is a multiplayer crash game. When you open it, you join a
            live room where everyone watches the same rounds, chats, and sees
            each other&apos;s results in real time. Here is how the live features
            work, and the honest truth about whether any of it helps you win.
          </p>
        </div>
      </section>

      {/* How live Aviator works */}
      <section className="border-b border-border py-16 lg:py-20">
        <div className="mx-auto max-w-4xl px-4 sm:px-6">
          <div className="rounded-2xl border border-primary/30 bg-primary/5 p-8">
            <h2 className="text-2xl font-bold tracking-tight md:text-3xl">
              One shared round for everyone
            </h2>
            <p className="mt-4 leading-relaxed text-muted-foreground">
              The core of live Aviator is simple: there is one round, and
              everyone in the room experiences it together. The plane takes off,
              the multiplier starts climbing from 1.00x, and at some unpredictable
              point it flies away and the round crashes. Every player sees the
              same crash point at the same moment. There are no private rounds or
              individual outcomes.
            </p>
            <p className="mt-4 leading-relaxed text-muted-foreground">
              Between rounds there is a short countdown so players can place
              bets for the next flight. This shared, ticking-clock rhythm is what
              makes live Aviator feel like a community game rather than a solo
              slot.
            </p>
          </div>

          <div className="mt-6 rounded-2xl border border-border bg-card p-8">
            <h2 className="text-2xl font-bold tracking-tight md:text-3xl">
              The live features: chat, bets, and wins
            </h2>
            <p className="mt-4 leading-relaxed text-muted-foreground">
              Around the main game screen, Aviator layers in several live
              elements that make the room feel busy and social:
            </p>
            <ul className="mt-4 space-y-3 text-sm leading-relaxed text-muted-foreground">
              <li className="flex gap-3">
                <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />
                <span>
                  <strong className="text-foreground">Live chat.</strong> A chat
                  window lets players talk during the round. Remember that chat
                  is unmoderated by the game itself, and it is full of hype, bad
                  advice, and people claiming to see patterns. Treat it as
                  entertainment, not a tip source.
                </span>
              </li>
              <li className="flex gap-3">
                <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />
                <span>
                  <strong className="text-foreground">Betting panel.</strong> A
                  list shows every player who has bet this round, their stake,
                  and the multiplier at which they cashed out. When someone hits
                  a big multiplier, it flashes in the panel and often in chat.
                </span>
              </li>
              <li className="flex gap-3">
                <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />
                <span>
                  <strong className="text-foreground">Live win feed.</strong> A
                  ticker highlights recent big wins across the room. This is
                  designed to feel exciting, but it can also create pressure to
                  chase multipliers. Step back when it gets loud.
                </span>
              </li>
            </ul>
          </div>
        </div>
      </section>

      {/* The live betting stats panel */}
      <section className="border-b border-border bg-secondary/30 py-16 lg:py-24">
        <div className="mx-auto max-w-4xl px-4 sm:px-6">
          <div className="max-w-2xl">
            <h2 className="text-3xl font-bold tracking-tight md:text-4xl">
              Reading the live betting panel
            </h2>
            <p className="mt-3 text-muted-foreground">
              The stats panel is the most data-rich part of live Aviator. It is
              useful for understanding the room, but it is not a prediction
              engine.
            </p>
          </div>

          <div className="mt-10 grid gap-6 md:grid-cols-2">
            <div className="rounded-2xl border border-border bg-card p-8">
              <h3 className="text-xl font-bold">What the panel shows</h3>
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                For each round you see player handles, bet sizes, and cash out
                multipliers. You also get recent round history with the crash
                points. This tells you how volatile the current room feels and
                how other players are sizing their bets.
              </p>
            </div>
            <div className="rounded-2xl border border-border bg-card p-8">
              <h3 className="text-xl font-bold">What it cannot tell you</h3>
              <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                The panel is historical. It shows what already happened, and past
                rounds have no bearing on the next one. A run of low crashes does
                not make a high crash &quot;due.&quot; Believing otherwise is the
                gambler&apos;s fallacy, and it is the fastest way to lose money.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Watching live won't help you win */}
      <section className="border-b border-border py-16 lg:py-20">
        <div className="mx-auto max-w-4xl px-4 sm:px-6">
          <div className="rounded-2xl border border-border bg-card p-8">
            <h2 className="text-2xl font-bold tracking-tight md:text-3xl">
              Watching live rounds will not help you win
            </h2>
            <p className="mt-4 leading-relaxed text-muted-foreground">
              This is the most important point on this page, so it deserves its
              own section. Aviator runs on a provably fair random number
              generator. Each round&apos;s crash point is determined independently
              by that RNG, and the result is not influenced by any previous
              round. A round that crashed at 1.05x does not make the next one
              more likely to go high. A round that hit 80x does not make the next
              one more likely to crash early.
            </p>
            <p className="mt-4 leading-relaxed text-muted-foreground">
              People who stare at the live history and announce patterns in the
              chat are seeing patterns in random noise. The human brain is wired
              to find trends, even where none exist. Casinos know this, which is
              why the history is shown so prominently. It encourages players to
              believe they can time the game. They cannot.
            </p>
            <p className="mt-4 leading-relaxed text-muted-foreground">
              What live viewing <em>can</em> do is help you learn the rhythm of
              the game: how fast multipliers climb, how the countdown between
              rounds works, and how it feels to wait for a cash out. That comfort
              is genuinely useful for a beginner. Just do not mistake it for an
              edge.
            </p>
          </div>

          <div className="mt-6 rounded-2xl border border-primary/30 bg-primary/5 p-8">
            <h3 className="text-xl font-bold">Practice without pressure</h3>
            <p className="mt-3 leading-relaxed text-muted-foreground">
              Before you risk real money, watch and play rounds in our free demo.
              It uses the same pacing and mechanics, so you can build a feel for
              the live rhythm with zero financial stress.
            </p>
            <Link
              href="/how-to-play/demo"
              className="mt-5 inline-flex items-center justify-center rounded-xl bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground transition-transform hover:scale-[1.02] active:scale-[0.98]"
            >
              Play Free Aviator Demo
            </Link>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="border-b border-border py-16 lg:py-24">
        <div className="mx-auto max-w-3xl px-4 sm:px-6">
          <h2 className="text-3xl font-bold tracking-tight md:text-4xl">
            Live Aviator questions, answered honestly
          </h2>
          <p className="mt-3 text-muted-foreground">
            Shared rounds, the betting panel, and whether any of it gives you an
            edge. (Spoiler: it does not.)
          </p>

          <div className="mt-10 space-y-4">
            {liveFaqs.map((faq) => (
              <div
                key={faq.question}
                className="rounded-2xl border border-border bg-card p-6"
              >
                <h3 className="font-semibold">{faq.question}</h3>
                <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
                  {faq.answer}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Bottom CTA */}
      <section className="py-16">
        <div className="mx-auto max-w-4xl px-4 sm:px-6">
          <div className="flex flex-col items-center justify-between gap-6 rounded-2xl border border-border bg-card p-8 text-center sm:flex-row sm:text-left">
            <div>
              <h2 className="text-2xl font-bold tracking-tight md:text-3xl">
                Get comfortable with the live rhythm first
              </h2>
              <p className="mt-2 text-muted-foreground">
                Watch and play rounds for free before joining a real-money room.
                Understanding the pace beats chasing a pattern that does not
                exist.
              </p>
            </div>
            <div className="flex flex-col gap-3 sm:flex-row">
              <Link
                href="/how-to-play/demo"
                className="inline-flex items-center justify-center rounded-xl bg-primary px-6 py-3.5 font-semibold text-primary-foreground transition-transform hover:scale-[1.02] active:scale-[0.98]"
              >
                Try the Free Demo
              </Link>
              <Link
                href="/how-to-play"
                className="inline-flex items-center justify-center rounded-xl border border-border bg-background px-6 py-3.5 font-semibold transition-colors hover:border-primary/50"
              >
                How to Play Aviator
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* JSON-LD */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema(liveFaqs)) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumb) }}
      />
    </>
  );
}
